### ISSUE TITLE
[Feature Request] Restructure CPP Code

### ISSUE THREAD

**Issue by 1chooo** [adpadillar/cpp-snake#1]
### Descriptions
Hi! @adpadillar , I deeply appreciate your dedication and hard work! Your impressive accomplishments have inspired me to fork your project and strive for further enhancements, despite the fact that you have already achieved outstanding results.

After reviewing the project structure, I recommend separating the `main.cpp` file into different cpp files to enhance future code maintenance convenience. I have relevant experience and would be willing to help you with this task. If you agree, I can fork this repository, make the necessary modifications, and submit the pull requests.

If you want to discuss more with me, please feel free to DM me.

BR,
@1chooo

**Comment by adpadillar** [comment]
Hi @1chooo

Go ahead! 

If you can, use the structure in the file structure in this repo: https://github.com/adpadillar/cpp-diagnostic

- src directory with a cpp file for each class
- include directory with the header files

In the project i reference there is a folder called "entrega", just ignore that.

I'll take a look at any pr's!

**Comment by 1chooo** [comment]
Hi! @adpadillar 

Thank you for your response! I will follow the structure you provided. Just give me a moment to make my small contribution.

@1chooo

**Comment by 1chooo** [comment]
Hi! @adpadillar 

I have initiated the pull request. Feel free to review it whenever you have time.

@1chooo
